### ISSUE TITLE
Open questions

### ISSUE THREAD

**Issue by ToonVanhoutte** [SeanFeldman/ServiceBus.CompressionPlugin#1]
Hey Sean,

great to see this plugin, thx for that!  I still had some open questions I didn't answer yet

_1/ Would you say any message going of a vessel would need to be compressed, or there's be some condition?_
**TVH**: Any message seems the most convenient to me.

_2/ If there's any conditions, what those would look like?_
**TVH**: Can't really think of conditions.  Maybe based on content-type?  Some probably don't benefit a lot from compression, but I don't think you should care within the plugin.

_3/ Would it matter what compression algorithm is used?_
**TVH**: GZIP seems most commonly accepted.

**Comment by SeanFeldman** [comment]
Thanks @ToonVanhoutte.
I think you'll be happy to find out that by default it uses GZip (default .NET implementation). Compression is applied from to message body of 1500 bytes and larger. Below that size it's not really efficient according to documentation. In addition to that, custom compression methods can be configured w/o the need to implement any classes (using `Func`s only).
Take it for a spin and hopefully will be able to ship a final version soon (pun was intended 🙂).

**Comment by ToonVanhoutte** [comment]
Super!!!
