### ISSUE TITLE
Allow configuring minimum message size for compression. 

### ISSUE THREAD

**Issue by msajid** [SeanFeldman/ServiceBus.CompressionPlugin#10]
Default message size in GzipCompressionConfiguration is 1500 bytes and there is no way to change it without supplying a compression configuration. 

One good solution could be making GzipCompressionConfiguration with minimum message size configurable.

**Comment by SeanFeldman** [comment]
Thank you @msajid.

1500 is the minimum size at which GZip can be effective. Below that size it's inefective. Is the idea you have is to control that size to instruct the plugin to compress from a size that is different than the recommended minimum, but not before certain size is reached (such as let's say 50K or another significantly bigger size than 1500 bytes)?

**Comment by msajid** [comment]
For production we use Service bus premium tier that has 1mb of message size limit (including header and body) and i would not like to compress messages unless body is larger than 500Ks. however, for dev/test scenarios we use standard tier which doesn't allow more than 256k of message size so configurable minimum message size would be very helpful.

**Comment by SeanFeldman** [comment]
That sounds like a scenario many would have (standard tier for testing and premium for production). Having configuration-based minimum size would be useful.

**Comment by SeanFeldman** [comment]
Fixed via https://github.com/SeanFeldman/ServiceBus.CompressionPlugin/commit/89abd17765c8e444bc27a86da8489b13b1e37d22

@msajid you'll be able to pass in minimum size for compression to use rather than rely on the default only.
