### ISSUE TITLE
Allow registration of multiple decompressors for message receiver

### ISSUE THREAD

**Issue by msajid** [SeanFeldman/ServiceBus.CompressionPlugin#11]
With multiple decompressors receiver can choose an appropriate decompressor based on the value in compression-method property in service bus message.

This feature could be handy in scenarios where multiple senders are sending message with different type of compression to same queue and one or more receiver receives and decompresses all the messages.

**Comment by SeanFeldman** [comment]
Thank you @msajid. Good suggestion.

**Comment by SeanFeldman** [comment]
Thinking about it a little more, #9 could be also addressed in a better way with this feature than the current recommendation.

```
### To transition to a different compression, compression callbacks need to be updated.

1. Update `compressor` callback to register a new compression method name.
2. Update `decompressor` callback to handle the old and the new compression method names.
3. Drain all messages compressed using the old compression method name.
4. Update `decompresson` callback to handle the new compression method only.
```

**Comment by SeanFeldman** [comment]
Thinking out loud - a plugin would always send out messages compressed with a single compression method, but would allow to receive additional compression methods.

@msajid how would you want to see the public API?

**Comment by msajid** [comment]
Since Servicebus plugin architecture allows multiple registrations, I achieved the desired result by registering multiple plugin instances at receiving side. it works because AfterMessageReceive simply forwards the original message to next plugin in the pipeline when the compression-method name doesn't match. 

This doesn't work with the same ClientEntity though. see #12

**Comment by msajid** [comment]
see #12

**Comment by SeanFeldman** [comment]
@msajid have a look at PR #13.
Looks like it will resolve this issue and will not require #12.

**Comment by SeanFeldman** [comment]
closed via https://github.com/SeanFeldman/ServiceBus.CompressionPlugin/commit/8237b411bf8f136b81ee88d926e237da4a92e356
