### ISSUE TITLE
How would you transition to a diff compression

### ISSUE THREAD

**Issue by SimonCropp** [SeanFeldman/ServiceBus.CompressionPlugin#9]
How would you transition to a diff compression when u have messages in transit?

**Comment by tomkerkhove** [comment]
Given there is a header being added when the message is queued with information about the used compression protocol the receiver should always be able to handle the decompression.

Unless I'm missing something this should work seamlessly, right @SeanFeldman?

**Comment by SimonCropp** [comment]
I agree that is an approach. But that is currently not implemented

**Comment by tomkerkhove** [comment]
Good news is - It is already implemented that way:

**Send:** *([source](https://github.com/SeanFeldman/ServiceBus.CompressionPlugin/blob/develop/src/ServiceBus.CompressionPlugin/CompressionPlugin.cs#L39))*
```csharp
message.UserProperties[Headers.CompressionMethodName] = configuration.CompressionMethodName;
```

**Receive:** *([source](https://github.com/SeanFeldman/ServiceBus.CompressionPlugin/blob/develop/src/ServiceBus.CompressionPlugin/CompressionPlugin.cs#L52))*
```csharp
if (!message.UserProperties.TryGetValue(Headers.CompressionMethodName, out var methodName) || (string)methodName != configuration.CompressionMethodName)
{
   return Task.FromResult(message);
}
```

**Comment by SeanFeldman** [comment]
Transitioning to a different compression or changing an already used compression would require changes to be made to the callbacks. Which is entirely under users control, as @tomkerkhove has pointed out.

For example, let's say `X` compression was originally used and project is transitioned to use `Y` compression. The compressing callback would stamp outgoing messages with the the new method, `Y`. While the de-compressing callback would need to check for both the old `X` method name and the new `Y` method name. Until all old messages have been drained and it's safe to drop the check for the old compression method name `X`.

With that, the compatibility is addressed and shouldn't be an issue. Agree @SimonCropp?

**Comment by SimonCropp** [comment]
Yep fair enough

**Comment by SeanFeldman** [comment]
I've [updated doco](https://github.com/SeanFeldman/ServiceBus.CompressionPlugin/commit/df7b582ed4f4ab90acb45cc35e1050ff9697a823) with a section based on the question raised here.
Thank you @SimonCropp.
